name: CI Pipeline - Insight Control

# O robô é ativado sempre que enviar código para a branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==========================================
  # 1. TESTE DO FRONTEND (Next.js)
  # ==========================================
  frontend-check:
    name: Verificação do Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Instalar Dependências e Simular Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

  # ==========================================
  # 2. TESTE DO BACKEND (FastAPI)
  # ==========================================
  backend-check:
    name: Verificação do Backend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar Dependências
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Verificação de Erros Críticos (Linting)
        working-directory: ./backend
        run: |
          # O Flake8 vai procurar erros graves de sintaxe no Python
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics